#{% set cuda_major = environ.get("cuda_compiler_version", "0.0").split(".")[0]|int %}

package:
  name: arborx
  version: "1.6"

source:
  url: https://github.com/arborx/ArborX/archive/refs/tags/v1.6.tar.gz
  sha1: fa7b1caa1b21a543bb95c4260c2d7a65de63644f
  patches:
    - findcuda.patch  # [cuda_compiler_version != "None"]

build:
  number: 0
  script_env:
    - CUDA_ARGS -DCMAKE_CXX_COMPILER=nvcc_wrapper  # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake >=3.16
    - kokkos >=4.3.0
    - make  # [not win]
  run:
    - kokkos >=4.3.0
    - __cuda   # [cuda_compiler_version != "None"]

test:
  commands:
    - test -f $PREFIX/include/ArborX/ArborX.hpp  # [linux]
    - test -f $PREFIX/include/ArborX/ArborX.hpp  # [osx]
    - if not exist %LIBRARY_BIN%\\include\\ArborX\\ArborX.hpp exit 1  # [win]

about:
  home: https://github.com/arborx/ArborX/
  summary: This module provides the header-only open-source library ArborX.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/arborx/ArborX/blob/master/LICENSE
  description: ArborX is an open-source library designed to provide performance portable algorithms for geometric search, similarly to nanoflann and Boost Geometry.
  doc_url: https://github.com/arborx/ArborX/wiki/
  dev_url: https://github.com/arborx/ArborX/

extra:
  recipe-maintainers:
    - Frayzen
    - fbordeu
    - messahelramzi
